-- Enable Row Level Security
ALTER TABLE IF EXISTS teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages ENABLE ROW LEVEL SECURITY;

-- 1. Teachers Table
CREATE TABLE IF NOT EXISTS teachers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  style TEXT,
  price TEXT,
  location TEXT,
  image TEXT,
  "videoThumb" TEXT,
  rating NUMERIC,
  bio TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policies for Teachers (Readable by everyone, writable by service role only for now)
DROP POLICY IF EXISTS "Public teachers are viewable by everyone" ON teachers;
CREATE POLICY "Public teachers are viewable by everyone" ON teachers FOR SELECT USING (true);


-- 2. Slots Table (Teacher Availability)
CREATE TABLE IF NOT EXISTS slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT REFERENCES teachers(id),
  date TEXT NOT NULL, -- YYYY-MM-DD
  time TEXT NOT NULL,
  status TEXT DEFAULT 'available', -- 'available', 'booked'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policies for Slots
DROP POLICY IF EXISTS "Slots are viewable by everyone" ON slots;
CREATE POLICY "Slots are viewable by everyone" ON slots FOR SELECT USING (true);
DROP POLICY IF EXISTS "Anyone can insert slots" ON slots;
CREATE POLICY "Anyone can insert slots" ON slots FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Anyone can update slots" ON slots;
CREATE POLICY "Anyone can update slots" ON slots FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Anyone can delete slots" ON slots;
CREATE POLICY "Anyone can delete slots" ON slots FOR DELETE USING (true);


-- 3. Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT REFERENCES teachers(id),
  student_id TEXT NOT NULL, -- Simplified ID
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  status TEXT DEFAULT 'upcoming',
  status_label TEXT DEFAULT 'Payé',
  slot_id BIGINT REFERENCES slots(id),
  price TEXT,
  location TEXT,
  style TEXT,
  teacher_name TEXT,
  teacher_image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policies for Bookings
DROP POLICY IF EXISTS "Bookings are viewable by everyone" ON bookings;
CREATE POLICY "Bookings are viewable by everyone" ON bookings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Anyone can insert bookings" ON bookings;
CREATE POLICY "Anyone can insert bookings" ON bookings FOR INSERT WITH CHECK (true);


-- 4. Chats Table
CREATE TABLE IF NOT EXISTS chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participants JSONB, -- Array of IDs [1, "student-1"]
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policies for Chats
DROP POLICY IF EXISTS "Chats are viewable by everyone" ON chats;
CREATE POLICY "Chats are viewable by everyone" ON chats FOR SELECT USING (true);
DROP POLICY IF EXISTS "Anyone can insert chats" ON chats;
CREATE POLICY "Anyone can insert chats" ON chats FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Anyone can update chats" ON chats;
CREATE POLICY "Anyone can update chats" ON chats FOR UPDATE USING (true);


-- 5. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id BIGINT REFERENCES chats(id),
  sender_id TEXT,
  text TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Policies for Messages
DROP POLICY IF EXISTS "Messages are viewable by everyone" ON messages;
CREATE POLICY "Messages are viewable by everyone" ON messages FOR SELECT USING (true);
DROP POLICY IF EXISTS "Anyone can insert messages" ON messages;
CREATE POLICY "Anyone can insert messages" ON messages FOR INSERT WITH CHECK (true);


-- INSERT INITIAL DATA (Mock Data Migration)

INSERT INTO teachers (name, style, price, location, rating, image, "videoThumb")
VALUES 
('Sophie Martin', 'Danse Classique', '65 CHF', 'Genève', 4.9, 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&q=80&w=200', 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&q=80&w=800'),
('Thomas Dubois', 'Hip Hop / Street', '45 CHF', 'Lausanne', 4.8, 'https://images.unsplash.com/photo-1535525266644-dc2230e199d8?auto=format&fit=crop&q=80&w=200', 'https://images.unsplash.com/photo-1535525266644-dc2230e199d8?auto=format&fit=crop&q=80&w=800'),
('Elena Rodriguez', 'Flamenco', '70 CHF', 'Genève', 5.0, 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?auto=format&fit=crop&q=80&w=200', 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?auto=format&fit=crop&q=80&w=800');
